name: docker build push

on:
  push:
    paths:
      - "Dockerfile"
      - ".github/workflows/docker-push.yml"   
    
env:
  # Use x for Docker Hub if empty. ghcr.io / docker.io
  REGISTRY: docker.io    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Check out the repo
      uses: actions/checkout@v2    
    - 
      name: Setup QEMU
      uses: docker/setup-qemu-action@v1

    - 
      name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - 
      name: Login into registry ${{ env.REGISTRY }}   
      uses: docker/login-action@v1      
      with:
        registry: ${{ env.REGISTRY }}   
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}   
    - 
      name: Prepare environment variables
      id: prepare
      run: |
        echo ::set-output name=docker_platforms::linux/amd64,linux/arm64,linux/386
        echo ::set-output name=docker_image::devcto/git
        echo ::set-output name=docker_is_push::true
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: ${{ steps.prepare.outputs.docker_platforms }}
        outputs: type=image
        push: ${{ steps.prepare.outputs.docker_is_push }}
        tags: ${{ steps.prepare.outputs.docker_image }}:latest
        file: Dockerfile

